using CoreAlign.Application.Common;
using CoreAlign.Application.Products.DTOs;
using CoreAlign.Domain.Enums;
using MediatR;

namespace CoreAlign.Application.Products.Commands;

public record CreateProductCommand(
    string Sku,
    string Name,
    string? Description = null,
    string? ShortDescription = null,
    string? Barcode = null,
    string? Mpn = null,
    string? Slug = null,
    Guid? BrandId = null,
    Guid? CategoryId = null,
    Guid? ParentProductId = null,
    string? VariantAttributesJson = null,
    string? TagsJson = null,
    string Unit = "pcs",
    Guid? BaseUomId = null,
    Guid? PurchaseUomId = null,
    Guid? SalesUomId = null,
    decimal Price = 0m,
    decimal ListPrice = 0m,
    decimal MinSellingPrice = 0m,
    decimal StandardCost = 0m,
    string Currency = "TRY",
    Guid? TaxRateId = null,
    bool IsPriceTaxInclusive = false,
    decimal StockQuantity = 0m,
    bool IsStockTracked = true,
    bool IsLotTracked = false,
    bool IsSerialTracked = false,
    bool RequiresInspection = false,
    decimal MinStock = 0m,
    decimal MaxStock = 0m,
    decimal ReorderPoint = 0m,
    decimal SafetyStock = 0m,
    int LeadTimeDays = 0,
    decimal? WeightKg = null,
    decimal? WidthCm = null,
    decimal? HeightCm = null,
    decimal? DepthCm = null,
    decimal? VolumeM3 = null,
    ProductStatus Status = ProductStatus.Active,
    DateTime? LaunchDate = null,
    DateTime? EndOfLifeDate = null,
    ProcurementType ProcurementType = ProcurementType.Buy,
    CostingMethod CostingMethod = CostingMethod.WeightedAverage,
    string? Color = null,
    decimal? ThicknessMm = null
) : IRequest<ProductDto>, ITransactionalRequest;

public record UpdateProductCommand(
    Guid Id,
    string Sku,
    string Name,
    string? Description,
    string? ShortDescription,
    string? Barcode,
    string? Mpn,
    string? Slug,
    Guid? BrandId,
    Guid? CategoryId,
    Guid? ParentProductId,
    string? VariantAttributesJson,
    string? TagsJson,
    string Unit,
    Guid? BaseUomId,
    Guid? PurchaseUomId,
    Guid? SalesUomId,
    decimal Price,
    decimal ListPrice,
    decimal MinSellingPrice,
    decimal StandardCost,
    string Currency,
    Guid? TaxRateId,
    bool IsPriceTaxInclusive,
    bool IsStockTracked,
    bool IsLotTracked,
    bool IsSerialTracked,
    bool? RequiresInspection,
    decimal MinStock,
    decimal MaxStock,
    decimal ReorderPoint,
    decimal SafetyStock,
    int LeadTimeDays,
    decimal? WeightKg,
    decimal? WidthCm,
    decimal? HeightCm,
    decimal? DepthCm,
    decimal? VolumeM3,
    ProductStatus Status,
    DateTime? LaunchDate,
    DateTime? EndOfLifeDate,
    ProcurementType ProcurementType = ProcurementType.Buy,
    CostingMethod CostingMethod = CostingMethod.WeightedAverage,
    string? Color = null,
    decimal? ThicknessMm = null
) : IRequest<ProductDto>, ITransactionalRequest;

public record DeleteProductCommand(Guid Id) : IRequest<bool>, ITransactionalRequest;
