export {
  applyPlanMoveSnap,
  lineProbePoints,
  snapDimensionMm,
  stickyDimensionMm,
  filterSnapTargets,
  EMPTY_SNAP_TARGETS,
  type PlanPoint,
  type PlanSnapPoint,
  type PlanSnapSegment,
  type PlanSnapTargets,
  type PlanMoveDelta,
  type PlanSnapGuide,
  type PlanSnapGuideKind,
  type PlanSnapResult,
} from '@/shared/three-engine';
