using CoreAlign.Domain.Enums;

namespace CoreAlign.Application.Manufacturing.DTOs;

public record ProductionJobListDto(
    Guid Id,
    string JobNumber,
    Guid ProductId,
    string ProductName,
    ProductionJobStatus Status,
    decimal PlannedQuantity,
    decimal CompletedQuantity,
    decimal ScrappedQuantity,
    string UnitOfMeasure,
    int? CurrentStepNumber,
    int StepCount,
    DateTime? DueDateUtc,
    DateTime CreatedAtUtc);

public record ProductionJobDetailDto(
    Guid Id,
    string JobNumber,
    Guid ProductId,
    string ProductName,
    ProductionJobStatus Status,
    decimal PlannedQuantity,
    decimal CompletedQuantity,
    decimal ScrappedQuantity,
    string UnitOfMeasure,
    Guid? WarehouseId,
    Guid? SourceRoutingId,
    string? RoutingCodeSnapshot,
    string? RoutingNameSnapshot,
    long? RoutingSnapshotVersion,
    int? CurrentStepNumber,
    DateTime? PlannedStartDateUtc,
    DateTime? DueDateUtc,
    DateTime? ReleasedAtUtc,
    DateTime? StartedAtUtc,
    DateTime? CompletedAtUtc,
    DateTime? CancelledAtUtc,
    string? CancellationReason,
    string? Notes,
    long ConcurrencyToken,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc,
    IReadOnlyList<ProductionJobStepDto> Steps);

public record ProductionJobStepDto(
    Guid Id,
    int StepNumber,
    Guid? WorkCenterId,
    string WorkCenterName,
    string OperationName,
    RoutingOperationType OperationType,
    ProductionJobStepStatus Status,
    bool IsOptional,
    decimal InputQuantity,
    decimal GoodQuantity,
    decimal ScrappedQuantity,
    decimal SetupTimeMinutes,
    decimal RunTimeMinutesPerUnit,
    decimal? RunTimeMinutesPerSqm,
    decimal ScrapPercentage,
    decimal? ActualSetupMinutes,
    decimal? ActualRunMinutes,
    Guid? AssignedOperatorId,
    DateTime? StartedAtUtc,
    DateTime? FinishedAtUtc,
    int ReworkCount,
    string? Instructions);
