// <auto-generated />
using CoreAlign.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CoreAlign.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoreAlignDbContext))]
    [Migration("20260602061305_Phase32PiiEncryption")]
    partial class Phase32PiiEncryption
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
