import type { Product, UpdateProductInput } from './product.types';

export const buildProductUpdateInput = (
  product: Product,
  overrides: Partial<Pick<UpdateProductInput, 'name' | 'description' | 'barcode'>> = {},
): UpdateProductInput => ({
  id: product.id,
  sku: product.sku,
  name: product.name,
  description: product.description,
  shortDescription: product.shortDescription,
  barcode: product.barcode,
  mpn: product.mpn,
  slug: product.slug,
  brandId: product.brandId,
  categoryId: product.categoryId,
  parentProductId: product.parentProductId,
  variantAttributesJson: product.variantAttributesJson,
  tagsJson: product.tagsJson,
  unit: product.unit,
  baseUomId: product.baseUomId,
  purchaseUomId: product.purchaseUomId,
  salesUomId: product.salesUomId,
  price: product.price,
  listPrice: product.listPrice,
  minSellingPrice: product.minSellingPrice,
  standardCost: product.standardCost,
  currency: product.currency,
  taxRateId: product.taxRateId,
  isPriceTaxInclusive: product.isPriceTaxInclusive,
  isStockTracked: product.isStockTracked,
  isLotTracked: product.isLotTracked,
  isSerialTracked: product.isSerialTracked,
  minStock: product.minStock,
  maxStock: product.maxStock,
  reorderPoint: product.reorderPoint,
  safetyStock: product.safetyStock,
  leadTimeDays: product.leadTimeDays,
  procurementType: product.procurementType,
  costingMethod: product.costingMethod,
  weightKg: product.weightKg,
  widthCm: product.widthCm,
  heightCm: product.heightCm,
  depthCm: product.depthCm,
  volumeM3: product.volumeM3,
  status: product.status,
  launchDate: product.launchDate,
  endOfLifeDate: product.endOfLifeDate,
  expectedConcurrencyToken: product.concurrencyToken,
  ...overrides,
});
