using CoreAlign.Application.Warranty;
using CoreAlign.Domain.Entities.Warranty;
using CoreAlign.Domain.Enums;
using CoreAlign.Domain.Events;
using CoreAlign.Domain.Interfaces;

namespace CoreAlign.Application.Tests.Warranty;

public class WarrantyContractServiceTests
{
    private readonly IWarrantyContractRepository _repo = Substitute.For<IWarrantyContractRepository>();
    private readonly WarrantyContractService _sut;

    public WarrantyContractServiceTests()
    {
        _sut = new WarrantyContractService(_repo);
    }

    [Fact]
    public async Task CreateAsync_persists_contract_with_autogenerated_number()
    {
        _repo.CountForNumberSequenceAsync(DateTime.UtcNow.Year, Arg.Any<CancellationToken>()).Returns(7);

        var contract = await _sut.CreateAsync(
            orderId: Guid.NewGuid(),
            customerId: Guid.NewGuid(),
            coverageType: WarrantyCoverageType.FullService,
            warrantyMonths: 24,
            termsJson: "{}");

        contract.Should().NotBeNull();
        contract.Number.Should().Be($"WC-{DateTime.UtcNow.Year}-00008");
        contract.WarrantyMonths.Should().Be(24);
        contract.Status.Should().Be(WarrantyContractStatus.Active);
        await _repo.Received(1).AddAsync(contract, Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task ActivateAsync_sets_start_date_and_raises_event()
    {
        var contract = BuildContract();
        _repo.GetByIdAsync(contract.Id, Arg.Any<CancellationToken>()).Returns(contract);
        var newStart = new DateTime(2026, 06, 04, 0, 0, 0, DateTimeKind.Utc);

        await _sut.ActivateAsync(contract.Id, newStart);

        contract.Status.Should().Be(WarrantyContractStatus.Active);
        contract.StartDate.Should().Be(newStart);
        contract.EndDate.Should().Be(newStart.AddMonths(contract.WarrantyMonths));
        contract.DomainEvents.Should().ContainSingle(e => e is WarrantyActivatedEvent);
        _repo.Received(1).Update(contract);
    }

    [Fact]
    public async Task ExtendAsync_increases_end_date_by_months_added()
    {
        var contract = BuildContract(warrantyMonths: 12);
        var originalEnd = contract.EndDate;
        _repo.GetByIdAsync(contract.Id, Arg.Any<CancellationToken>()).Returns(contract);

        await _sut.ExtendAsync(contract.Id, monthsAdded: 6, reason: "Customer upgrade");

        contract.EndDate.Should().Be(originalEnd.AddMonths(6));
        contract.WarrantyMonths.Should().Be(18);
        contract.DomainEvents.Should().Contain(e => e is WarrantyExtendedEvent);
        _repo.Received(1).Update(contract);
    }

    [Fact]
    public async Task CancelAsync_marks_status_cancelled_and_records_reason()
    {
        var contract = BuildContract();
        _repo.GetByIdAsync(contract.Id, Arg.Any<CancellationToken>()).Returns(contract);

        await _sut.CancelAsync(contract.Id, reason: "Customer request");

        contract.Status.Should().Be(WarrantyContractStatus.Cancelled);
        contract.CancellationReason.Should().Be("Customer request");
        contract.DomainEvents.Should().Contain(e => e is WarrantyCancelledEvent);
        _repo.Received(1).Update(contract);
    }

    [Fact]
    public async Task ActivateAsync_throws_when_contract_missing()
    {
        _repo.GetByIdAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>()).Returns((WarrantyContract?)null);

        var act = () => _sut.ActivateAsync(Guid.NewGuid(), DateTime.UtcNow);

        await act.Should().ThrowAsync<KeyNotFoundException>();
    }

    private static WarrantyContract BuildContract(int warrantyMonths = 12)
    {
        var c = new WarrantyContract(
            orderId: Guid.NewGuid(),
            customerId: Guid.NewGuid(),
            number: "WC-2026-00001",
            coverageType: WarrantyCoverageType.FullService,
            startDate: new DateTime(2026, 01, 01, 0, 0, 0, DateTimeKind.Utc),
            warrantyMonths: warrantyMonths,
            termsJson: "{}");
        c.Id = Guid.NewGuid();
        c.ClearDomainEvents();
        return c;
    }
}
