// @ts-nocheck
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export interface IClient {
  /**
   * @param customerId (optional)
   * @return OK
   */
  dealerAccountsGET(customerId?: string | undefined): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  dealerAccountsPOST(body?: CreateDealerAccountCommand | undefined): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  dealerAccountsPUT(id: string, body?: UpdateDealerAccountCommand | undefined): Promise<void>;
  /**
   * @param dealerAccountId (optional)
   * @param customerId (optional)
   * @return OK
   */
  dealerCustomerLinksGET(
    dealerAccountId?: string | undefined,
    customerId?: string | undefined,
  ): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  dealerCustomerLinksPOST(body?: LinkDealerToCustomerCommand | undefined): Promise<void>;
  /**
   * @param reason (optional)
   * @return OK
   */
  dealerCustomerLinksDELETE(id: string, reason?: string | undefined): Promise<void>;
  /**
   * @return OK
   */
  dashboard(): Promise<void>;
  /**
   * @return OK
   */
  customers(): Promise<void>;
  /**
   * @param status (optional)
   * @param approvalStatus (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  ordersGET(
    status?: string | undefined,
    approvalStatus?: string | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
  ): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  ordersPOST(body?: CreateDealerOrderCommand | undefined): Promise<void>;
  /**
   * @return OK
   */
  ordersGET2(id: string): Promise<void>;
  /**
   * @return OK
   */
  revisionsGET(id: string): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  revisionsPOST(id: string, body?: DealerRequestRevisionRequest | undefined): Promise<void>;
  /**
   * @return OK
   */
  approve(id: string, revisionId: string): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  reject(
    id: string,
    revisionId: string,
    body?: DealerRejectRevisionRequest | undefined,
  ): Promise<void>;
  /**
   * @return OK
   */
  cancel(id: string, revisionId: string): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  cancel2(id: string, body?: CancelDealerOrderRequest | undefined): Promise<void>;
  /**
   * @param search (optional)
   * @param customerId (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  products(
    search?: string | undefined,
    customerId?: string | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
  ): Promise<void>;
  /**
   * @return OK
   */
  commentsGET(orderId: string): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  commentsPOST(orderId: string, body?: PostDealerOrderCommentRequest | undefined): Promise<void>;
  /**
   * @return OK
   */
  pdf(id: string): Promise<void>;
  /**
   * @param customerId (optional)
   * @param status (optional)
   * @param fromUtc (optional)
   * @param toUtc (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  invoices(
    customerId?: string | undefined,
    status?: string | undefined,
    fromUtc?: Date | undefined,
    toUtc?: Date | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
  ): Promise<void>;
  /**
   * @return OK
   */
  invoices2(id: string): Promise<void>;
  /**
   * @return OK
   */
  pdf2(id: string): Promise<void>;
  /**
   * @param status (optional)
   * @param fromUtc (optional)
   * @param toUtc (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  commissions(
    status?: DealerCommissionStatus | undefined,
    fromUtc?: Date | undefined,
    toUtc?: Date | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
  ): Promise<void>;
  /**
   * @return OK
   */
  summary(): Promise<void>;
  /**
   * @param fromUtc (optional)
   * @param toUtc (optional)
   * @return OK
   */
  pdf3(fromUtc?: Date | undefined, toUtc?: Date | undefined): Promise<void>;
  /**
   * @return OK
   */
  profile(): Promise<void>;
  /**
   * @return OK
   */
  credit(id: string): Promise<void>;
  /**
   * @param dealerAccountId (optional)
   * @return OK
   */
  dealerUsersGET(dealerAccountId?: string | undefined): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  dealerUsersPOST(body?: InviteDealerUserCommand | undefined): Promise<void>;
  /**
   * @param body (optional)
   * @return OK
   */
  status(id: string, body?: UpdateDealerUserStatusCommand | undefined): Promise<void>;
  /**
   * @param unreadOnly (optional)
   * @param take (optional)
   * @return OK
   */
  notifications(unreadOnly?: boolean | undefined, take?: number | undefined): Promise<void>;
  /**
   * @return OK
   */
  unreadCount(): Promise<void>;
  /**
   * @return OK
   */
  read(id: string): Promise<void>;
  /**
   * @return OK
   */
  readAll(): Promise<void>;
}

export class Client implements IClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param customerId (optional)
   * @return OK
   */
  dealerAccountsGET(customerId?: string | undefined, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-accounts?';
    if (customerId === null) throw new Error("The parameter 'customerId' cannot be null.");
    else if (customerId !== undefined)
      url_ += 'customerId=' + encodeURIComponent('' + customerId) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerAccountsGET(_response);
      });
  }

  protected processDealerAccountsGET(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  dealerAccountsPOST(
    body?: CreateDealerAccountCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-accounts';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerAccountsPOST(_response);
      });
  }

  protected processDealerAccountsPOST(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  dealerAccountsPUT(
    id: string,
    body?: UpdateDealerAccountCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-accounts/{id}';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'PUT',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerAccountsPUT(_response);
      });
  }

  protected processDealerAccountsPUT(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param dealerAccountId (optional)
   * @param customerId (optional)
   * @return OK
   */
  dealerCustomerLinksGET(
    dealerAccountId?: string | undefined,
    customerId?: string | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-customer-links?';
    if (dealerAccountId === null)
      throw new Error("The parameter 'dealerAccountId' cannot be null.");
    else if (dealerAccountId !== undefined)
      url_ += 'dealerAccountId=' + encodeURIComponent('' + dealerAccountId) + '&';
    if (customerId === null) throw new Error("The parameter 'customerId' cannot be null.");
    else if (customerId !== undefined)
      url_ += 'customerId=' + encodeURIComponent('' + customerId) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerCustomerLinksGET(_response);
      });
  }

  protected processDealerCustomerLinksGET(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  dealerCustomerLinksPOST(
    body?: LinkDealerToCustomerCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-customer-links';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerCustomerLinksPOST(_response);
      });
  }

  protected processDealerCustomerLinksPOST(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param reason (optional)
   * @return OK
   */
  dealerCustomerLinksDELETE(
    id: string,
    reason?: string | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-customer-links/{id}?';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    if (reason === null) throw new Error("The parameter 'reason' cannot be null.");
    else if (reason !== undefined) url_ += 'reason=' + encodeURIComponent('' + reason) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'DELETE',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerCustomerLinksDELETE(_response);
      });
  }

  protected processDealerCustomerLinksDELETE(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  dashboard(signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/dashboard';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDashboard(_response);
      });
  }

  protected processDashboard(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  customers(signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/customers';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCustomers(_response);
      });
  }

  protected processCustomers(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param status (optional)
   * @param approvalStatus (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  ordersGET(
    status?: string | undefined,
    approvalStatus?: string | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders?';
    if (status === null) throw new Error("The parameter 'status' cannot be null.");
    else if (status !== undefined) url_ += 'status=' + encodeURIComponent('' + status) + '&';
    if (approvalStatus === null) throw new Error("The parameter 'approvalStatus' cannot be null.");
    else if (approvalStatus !== undefined)
      url_ += 'approvalStatus=' + encodeURIComponent('' + approvalStatus) + '&';
    if (page === null) throw new Error("The parameter 'page' cannot be null.");
    else if (page !== undefined) url_ += 'page=' + encodeURIComponent('' + page) + '&';
    if (pageSize === null) throw new Error("The parameter 'pageSize' cannot be null.");
    else if (pageSize !== undefined) url_ += 'pageSize=' + encodeURIComponent('' + pageSize) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processOrdersGET(_response);
      });
  }

  protected processOrdersGET(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  ordersPOST(body?: CreateDealerOrderCommand | undefined, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processOrdersPOST(_response);
      });
  }

  protected processOrdersPOST(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  ordersGET2(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processOrdersGET2(_response);
      });
  }

  protected processOrdersGET2(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  revisionsGET(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/revisions';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRevisionsGET(_response);
      });
  }

  protected processRevisionsGET(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  revisionsPOST(
    id: string,
    body?: DealerRequestRevisionRequest | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/revisions';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRevisionsPOST(_response);
      });
  }

  protected processRevisionsPOST(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  approve(id: string, revisionId: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/revisions/{revisionId}/approve';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    if (revisionId === undefined || revisionId === null)
      throw new Error("The parameter 'revisionId' must be defined.");
    url_ = url_.replace('{revisionId}', encodeURIComponent('' + revisionId));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'POST',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processApprove(_response);
      });
  }

  protected processApprove(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  reject(
    id: string,
    revisionId: string,
    body?: DealerRejectRevisionRequest | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/revisions/{revisionId}/reject';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    if (revisionId === undefined || revisionId === null)
      throw new Error("The parameter 'revisionId' must be defined.");
    url_ = url_.replace('{revisionId}', encodeURIComponent('' + revisionId));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processReject(_response);
      });
  }

  protected processReject(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  cancel(id: string, revisionId: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/revisions/{revisionId}/cancel';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    if (revisionId === undefined || revisionId === null)
      throw new Error("The parameter 'revisionId' must be defined.");
    url_ = url_.replace('{revisionId}', encodeURIComponent('' + revisionId));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'POST',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCancel(_response);
      });
  }

  protected processCancel(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  cancel2(
    id: string,
    body?: CancelDealerOrderRequest | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/cancel';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCancel2(_response);
      });
  }

  protected processCancel2(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param search (optional)
   * @param customerId (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  products(
    search?: string | undefined,
    customerId?: string | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/catalog/products?';
    if (search === null) throw new Error("The parameter 'search' cannot be null.");
    else if (search !== undefined) url_ += 'search=' + encodeURIComponent('' + search) + '&';
    if (customerId === null) throw new Error("The parameter 'customerId' cannot be null.");
    else if (customerId !== undefined)
      url_ += 'customerId=' + encodeURIComponent('' + customerId) + '&';
    if (page === null) throw new Error("The parameter 'page' cannot be null.");
    else if (page !== undefined) url_ += 'page=' + encodeURIComponent('' + page) + '&';
    if (pageSize === null) throw new Error("The parameter 'pageSize' cannot be null.");
    else if (pageSize !== undefined) url_ += 'pageSize=' + encodeURIComponent('' + pageSize) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processProducts(_response);
      });
  }

  protected processProducts(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  commentsGET(orderId: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{orderId}/comments';
    if (orderId === undefined || orderId === null)
      throw new Error("The parameter 'orderId' must be defined.");
    url_ = url_.replace('{orderId}', encodeURIComponent('' + orderId));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCommentsGET(_response);
      });
  }

  protected processCommentsGET(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  commentsPOST(
    orderId: string,
    body?: PostDealerOrderCommentRequest | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{orderId}/comments';
    if (orderId === undefined || orderId === null)
      throw new Error("The parameter 'orderId' must be defined.");
    url_ = url_.replace('{orderId}', encodeURIComponent('' + orderId));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCommentsPOST(_response);
      });
  }

  protected processCommentsPOST(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  pdf(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/orders/{id}/pdf';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processPdf(_response);
      });
  }

  protected processPdf(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param customerId (optional)
   * @param status (optional)
   * @param fromUtc (optional)
   * @param toUtc (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  invoices(
    customerId?: string | undefined,
    status?: string | undefined,
    fromUtc?: Date | undefined,
    toUtc?: Date | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/invoices?';
    if (customerId === null) throw new Error("The parameter 'customerId' cannot be null.");
    else if (customerId !== undefined)
      url_ += 'customerId=' + encodeURIComponent('' + customerId) + '&';
    if (status === null) throw new Error("The parameter 'status' cannot be null.");
    else if (status !== undefined) url_ += 'status=' + encodeURIComponent('' + status) + '&';
    if (fromUtc === null) throw new Error("The parameter 'fromUtc' cannot be null.");
    else if (fromUtc !== undefined)
      url_ += 'fromUtc=' + encodeURIComponent(fromUtc ? '' + fromUtc.toISOString() : '') + '&';
    if (toUtc === null) throw new Error("The parameter 'toUtc' cannot be null.");
    else if (toUtc !== undefined)
      url_ += 'toUtc=' + encodeURIComponent(toUtc ? '' + toUtc.toISOString() : '') + '&';
    if (page === null) throw new Error("The parameter 'page' cannot be null.");
    else if (page !== undefined) url_ += 'page=' + encodeURIComponent('' + page) + '&';
    if (pageSize === null) throw new Error("The parameter 'pageSize' cannot be null.");
    else if (pageSize !== undefined) url_ += 'pageSize=' + encodeURIComponent('' + pageSize) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processInvoices(_response);
      });
  }

  protected processInvoices(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  invoices2(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/invoices/{id}';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processInvoices2(_response);
      });
  }

  protected processInvoices2(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  pdf2(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/invoices/{id}/pdf';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processPdf2(_response);
      });
  }

  protected processPdf2(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param status (optional)
   * @param fromUtc (optional)
   * @param toUtc (optional)
   * @param page (optional)
   * @param pageSize (optional)
   * @return OK
   */
  commissions(
    status?: DealerCommissionStatus | undefined,
    fromUtc?: Date | undefined,
    toUtc?: Date | undefined,
    page?: number | undefined,
    pageSize?: number | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/commissions?';
    if (status === null) throw new Error("The parameter 'status' cannot be null.");
    else if (status !== undefined) url_ += 'status=' + encodeURIComponent('' + status) + '&';
    if (fromUtc === null) throw new Error("The parameter 'fromUtc' cannot be null.");
    else if (fromUtc !== undefined)
      url_ += 'fromUtc=' + encodeURIComponent(fromUtc ? '' + fromUtc.toISOString() : '') + '&';
    if (toUtc === null) throw new Error("The parameter 'toUtc' cannot be null.");
    else if (toUtc !== undefined)
      url_ += 'toUtc=' + encodeURIComponent(toUtc ? '' + toUtc.toISOString() : '') + '&';
    if (page === null) throw new Error("The parameter 'page' cannot be null.");
    else if (page !== undefined) url_ += 'page=' + encodeURIComponent('' + page) + '&';
    if (pageSize === null) throw new Error("The parameter 'pageSize' cannot be null.");
    else if (pageSize !== undefined) url_ += 'pageSize=' + encodeURIComponent('' + pageSize) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCommissions(_response);
      });
  }

  protected processCommissions(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  summary(signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/commissions/summary';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processSummary(_response);
      });
  }

  protected processSummary(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param fromUtc (optional)
   * @param toUtc (optional)
   * @return OK
   */
  pdf3(fromUtc?: Date | undefined, toUtc?: Date | undefined, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/commissions/statement/pdf?';
    if (fromUtc === null) throw new Error("The parameter 'fromUtc' cannot be null.");
    else if (fromUtc !== undefined)
      url_ += 'fromUtc=' + encodeURIComponent(fromUtc ? '' + fromUtc.toISOString() : '') + '&';
    if (toUtc === null) throw new Error("The parameter 'toUtc' cannot be null.");
    else if (toUtc !== undefined)
      url_ += 'toUtc=' + encodeURIComponent(toUtc ? '' + toUtc.toISOString() : '') + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processPdf3(_response);
      });
  }

  protected processPdf3(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  profile(signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/profile';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processProfile(_response);
      });
  }

  protected processProfile(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  credit(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-portal/customers/{id}/credit';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCredit(_response);
      });
  }

  protected processCredit(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param dealerAccountId (optional)
   * @return OK
   */
  dealerUsersGET(dealerAccountId?: string | undefined, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-users?';
    if (dealerAccountId === null)
      throw new Error("The parameter 'dealerAccountId' cannot be null.");
    else if (dealerAccountId !== undefined)
      url_ += 'dealerAccountId=' + encodeURIComponent('' + dealerAccountId) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerUsersGET(_response);
      });
  }

  protected processDealerUsersGET(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  dealerUsersPOST(body?: InviteDealerUserCommand | undefined, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-users';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDealerUsersPOST(_response);
      });
  }

  protected processDealerUsersPOST(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  status(
    id: string,
    body?: UpdateDealerUserStatusCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/dealer-users/{id}/status';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'PUT',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processStatus(_response);
      });
  }

  protected processStatus(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param unreadOnly (optional)
   * @param take (optional)
   * @return OK
   */
  notifications(
    unreadOnly?: boolean | undefined,
    take?: number | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/notifications?';
    if (unreadOnly === null) throw new Error("The parameter 'unreadOnly' cannot be null.");
    else if (unreadOnly !== undefined)
      url_ += 'unreadOnly=' + encodeURIComponent('' + unreadOnly) + '&';
    if (take === null) throw new Error("The parameter 'take' cannot be null.");
    else if (take !== undefined) url_ += 'take=' + encodeURIComponent('' + take) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processNotifications(_response);
      });
  }

  protected processNotifications(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  unreadCount(signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/notifications/unread-count';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processUnreadCount(_response);
      });
  }

  protected processUnreadCount(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  read(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/notifications/{id}/read';
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'POST',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRead(_response);
      });
  }

  protected processRead(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  readAll(signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + '/api/v1/notifications/read-all';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'POST',
      url: url_,
      headers: {},
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processReadAll(_response);
      });
  }

  protected processReadAll(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }
}

export interface CancelDealerOrderRequest {
  reason?: string | null;
}

export interface DealerRejectRevisionRequest {
  reason?: string;
}

export interface DealerRequestRevisionRequest {
  proposedLines?: RevisionLineInput[];
  requestNotes?: string | null;
}

export interface PostDealerOrderCommentRequest {
  body?: string;
}

export interface CreateDealerAccountCommand {
  code?: string;
  name?: string;
  primaryCustomerId?: string | null;
  legalName?: string | null;
  taxNumber?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  notes?: string | null;
  currentUserId?: string;
  currentUserRoles?: string[] | null;
}

export interface CreateDealerOrderCommand {
  customerId?: string;
  lines?: DealerOrderLineInput[];
  notes?: string | null;
  currency?: string | null;
  customerNotes?: string | null;
  shippingAddressId?: string | null;
  billingAddressId?: string | null;
}

export interface DealerOrderLineInput {
  productId?: string;
  quantity?: number;
  unitPrice?: number | null;
  lineNotes?: string | null;
}

export interface InviteDealerUserCommand {
  dealerAccountId?: string;
  email?: string;
  firstName?: string | null;
  lastName?: string | null;
  role?: DealerMembershipRole;
  currentUserId?: string;
  currentUserRoles?: string[] | null;
}

export interface LinkDealerToCustomerCommand {
  dealerAccountId?: string;
  customerId?: string;
  notes?: string | null;
  currentUserId?: string;
  currentUserRoles?: string[] | null;
}

export interface UpdateDealerAccountCommand {
  id?: string;
  name?: string;
  legalName?: string | null;
  taxNumber?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  notes?: string | null;
  currentUserId?: string;
  currentUserRoles?: string[] | null;
}

export interface UpdateDealerUserStatusCommand {
  id?: string;
  status?: MembershipStatus;
  reason?: string | null;
  currentUserId?: string;
  currentUserRoles?: string[] | null;
}

export interface RevisionLineInput {
  productId?: string;
  quantity?: number;
  unitPrice?: number;
  lineNumber?: number;
  lineDiscountPercent?: number;
  lineDiscountAmount?: number;
  taxRatePercent?: number;
  isTaxInclusive?: boolean;
  withholdingRatePercent?: number;
  lineNotes?: string | null;
}

export enum DealerCommissionStatus {
  Accrued = 'Accrued',
  Paid = 'Paid',
  Cancelled = 'Cancelled',
}

export enum DealerMembershipRole {
  DealerOwner = 'DealerOwner',
  DealerStaff = 'DealerStaff',
}

export enum MembershipStatus {
  Active = 'Active',
  Suspended = 'Suspended',
  Archived = 'Archived',
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  throw new ApiException(message, status, response, headers, result);
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true;
}
